### ISSUE TITLE
Support for `connect_info` extractor?

### ISSUE THREAD

**Issue by MarcoLugo** [JosephLenton/axum-test#103] opened 2024-08-31 00:57 UTC
Maybe [connect_info](https://docs.rs/axum/latest/axum/extract/connect_info/struct.ConnectInfo.html) is supported but I haven't managed to find how to go around this yet. Is there currently a way to make this work? The error message seems to suggest built-in support is missing.

```
use std::net::SocketAddr;
use axum::{
    extract::ConnectInfo,
    Router,
    routing::get
};
use axum_test::TestServerConfig;

async fn get_ip(connect_info: ConnectInfo<SocketAddr>) -> String {
    connect_info.ip().to_string()
}

#[tokio::test]
async fn test_connect_info() {
    let app = Router::new().route("/ip", get(get_ip));

    let server = TestServerConfig::builder()
        .http_transport()
        .build_server(app)
        .unwrap();

    let response = server.get("/ip").await;

    dbg!(response.text());
    response.assert_status_ok();
}
```
When run, throws:
```
---- test_connect_info stdout ----
[src/lib.rs:24:5] response.text() = "Missing request extension: Extension of type `axum::extract::connect_info::ConnectInfo<core::net::socket_addr::SocketAddr>` was not found. Perhaps you forgot to add it? See `axum::Extension`."
thread 'test_connect_info' panicked at src/lib.rs:25:14:
assertion failed: `(left == right)`: Expected status code to be 200 (OK), received 500 (Internal Server Error), for request GET http://127.0.0.1:8000/ip

Diff < left / right > :
<200
>500
```

Thank you.

**Comment by JosephLenton** [comment] 2024-08-31 08:44
Hey @MarcoLugo , the issue is that to get Axum to pick up the connection info you need to turn the `Router` into a `MakeServiceWithConnectInfo`.

Change:
```rust
let app = Router::new().route("/ip", get(get_ip));
```

to:
```rust
let app = Router::new().route("/ip", get(get_ip))
            .into_make_service_with_connect_info::<SocketAddr>();
```

Your full code would be:
```rust
use std::net::SocketAddr;
use axum::{
    extract::ConnectInfo,
    Router,
    routing::get
};
use axum_test::TestServerConfig;

async fn get_ip(connect_info: ConnectInfo<SocketAddr>) -> String {
    connect_info.ip().to_string()
}

#[tokio::test]
async fn test_connect_info() {
    let app = Router::new().route("/ip", get(get_ip))
        .into_make_service_with_connect_info::<SocketAddr>();

    let server = TestServerConfig::builder()
        .http_transport()
        .build_server(app)
        .unwrap();

    let response = server.get("/ip").await;

    dbg!(response.text());
    response.assert_status_ok();
}
```

I am currently in the process of rewriting the docs and cleaning up the API a little. I can add an example of doing this to make it clearer.

**Comment by JosephLenton** [comment] 2024-09-05 13:17
Hey @MarcoLugo I have just closed this as it should work if you update your code.

If you feel there is more I can do, or I’ve missed something, then please do reopen this issue.

**Closed** 2024-09-05 13:16 UTC

**Comment by MarcoLugo** [comment] 2024-09-08 20:15
Sorry, @JosephLenton I was away for a little while. Thank you, this works perfectly! And thank you for creating this crate, it's a really nice addition to the ecosystem.
